### ISSUE TITLE
Final Launch Checklist

### ISSUE THREAD

**Issue by saliksyed** [VALIS-software/VALIS-frontend#195]
Goals
- [x] Add data to Firebase for all Chromosomes
- [x] Add a way to switch Chromosomes
- [x] Add track button should work for variant results
- [x] Check that all logging is functional and capturing the data that we want.
- [x] BONUS: With Multiple Panels the track edit header stops working -- make multiple panels work
- [x] Closable tracks
- [x] Macro variants so it's easy to find data in the query tracks
Added by @saliksyed
- [x] GTEXPortal Tracks should work
The bonus tasks we can try to hit. If we do not we can remove them for the alpha v0.
- [x] Clicking a track element (variant, gene annotation, etc) should bring up the entity details page
- [x] Make sure ENCODE Promoter Enhancer Tracks work (just need to show the intervals)
- [x] Vertical panning should work if we add more than a few tracks
- [x] BONUS: Check that boolean tracks work or remove the link from details panel
Added by @haxiomic 
- [x]  BONUS: Add sequence and strand tracks, @haxiomic
